project:
  type: website

format:
  html:
    theme: default        # (or default, darkly, etc.)
    toc: true             # page-level table of contents
    toc-depth: 2          # how deep headers go in TOC
    code-tools: false     # hide copy/download/run buttons
    code-fold: show       # collapsible code chunks
    code-overflow: wrap   # wrap long code lines
    smooth-scroll: true

jupyter: python3

execute:
  echo: true
  output: true
  warning: false
  error: false
  cache: false

link-external-newwindow: true

website:
  title: "Data Dunkers LMS"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: notebooks/notebooks.qmd
        text: Notebooks
      - text: "Slideshows"
        menu:
          - href: slides/intro.qmd
            text: "Quarto Process"
          - href: slides/tcdsb.qmd
            text: "TCDSB Slideshow (from Google Slides)"
  sidebar:
    style: docked
    contents:
      # - href: index.qmd
      #   text: "Home"
      - section: "Module 1"
        contents: 
          - module-1-welcome-to-data-dunkers/01-welcome.qmd
          - module-1-welcome-to-data-dunkers/02-what-is-data-dunkers.qmd
          - module-1-welcome-to-data-dunkers/03-flavors-of-the-program.qmd
          - module-1-welcome-to-data-dunkers/04-the-fundamentals-game-plan.qmd
          - module-1-welcome-to-data-dunkers/05-creating-your-playbook.qmd
      - section: "Module 2"
        contents: 
          - module-2-step-into-the-game-experience-like-a-student/01-welcome-to-the-court.qmd
          - module-2-step-into-the-game-experience-like-a-student/02-data-is-everywhere.qmd
          - module-2-step-into-the-game-experience-like-a-student/03-quick-timeout-look-at-jupyter-notebook.qmd
          - module-2-step-into-the-game-experience-like-a-student/04-labyrinth-activity.qmd
          - module-2-step-into-the-game-experience-like-a-student/05-to-understanding-the-instructional-approach.qmd
      - section: "Module 3"
        contents: 
          - section: "Planning Toolkit"
            contents:
              - module-3-implementation-in-your-context/1-planning-toolkit/01-align-activities-to-curriculum.qmd
              # - module-3-implementation-in-your-context/1-planning-toolkit/02-implementation-checklist.qmd
              - module-3-implementation-in-your-context/1-planning-toolkit/03-map-instructional-flow.qmd
              - module-3-implementation-in-your-context/1-planning-toolkit/04-select-datasets-and-themes.qmd
              # - module-3-implementation-in-your-context/1-planning-toolkit/05-strategies-for-grouping-and-facilitation.qmd
          - section: "Coding Lab: Basketball Data"
            contents:
              - module-3-implementation-in-your-context/2-coding-lab-basketball-data/import-and-prepare-data.qmd
