name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python + Jupyter
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jupyter ipykernel nbformat pyyaml plotly

      - name: Render and publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

